--- 
- hosts: all
 # gather_facts: false
  
  vars:
    mail_info: yes
    admin_mail: wissam.bteich@bmbgroup.com
    auto_reboot: yes
 
  tasks:
  - name: yum upgrade
    yum: name=* state=latest
    register: data_yum
    when: ansible_pkg_mgr == 'yum'
 
  - name: yum reboot-check
    shell: 'if [ "$(rpm -q kernel --queryformat ''%{installtime} %{version}-%{release}.%{arch}\n'' | sort -n -k1 | tail -1 | cut -d '' '' -f 2)" = "$(uname -r)" ]; then echo "no"; else echo "yes"; fi'
    register: reboot_yum
    when: ansible_pkg_mgr == 'yum'
 
  - name: yum summary
    shell: 'echo {{ data_yum.results | join(" ") | quote }} | mail -s "[ANSIBLE] Upgraded {{ ansible_fqdn }}" "{{ admin_mail }}"'
    when: ansible_pkg_mgr == 'yum' and data_yum.changed
 
  - name: reboot mail
    shell: 'echo "Reboot required on {{ ansible_fqdn }}" | mail -s "[ANSIBLE] Reboot required on {{ ansible_fqdn }}" "{{ admin_mail }}"'
    when: auto_reboot == 'no' and ( ansible_pkg_mgr == 'yum' and reboot_yum.stdout == 'yes' or ansible_pkg_mgr == 'apt' and reboot_apt.stdout == 'yes' )
 
  - name: auto-reboot
    command: shutdown -r now 'Rebooting to complete system upgrade'
    when: auto_reboot == 'yes' and ( ansible_pkg_mgr == 'yum' and reboot_yum.stdout == 'yes' or ansible_pkg_mgr == 'apt' and reboot_apt.stdout == 'yes' )
 
